accounts/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'login/$', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    re_path(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'signup/$', views.SignUp.as_view(), name='signup'),
]

orbit_connect/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from django.urls import include
from orbit_connect import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.HomePage.as_view(), name='home'),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^test/$', views.TestPage.as_view(), name='test'),
    re_path(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    re_path(r'^posts/', include('posts.urls', namespace='posts')),
    re_path(r'^groups/', include('groups.urls', namespace='groups')),
]

posts/urls.py
from django.urls import re_path
from posts import views

app_name = 'posts'

urlpatterns = [
    re_path(r'^$', views.PostList.as_view(), name='all'),
    re_path(r'^new/$', views.CreatePost.as_view(), name='create'),
    re_path(r'^by/(?P<username>[-\w]+)$',
            views.UserPosts.as_view(), name='for_user'),
    re_path(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',
            views.PostDetail.as_view(), name='single'),
    re_path(r'^delete/(?P<pk>\d+)/$',
            views.DeletePost.as_view(), name='delete'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OrbitConnect</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">

    <link rel="stylesheet" href="{% static 'orbit_connect/css/master.css' %}">

</head>
<body>

    <nav class='navbar mynav' role='navigation' id='navbar'>
        <div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">OrbitConnect</a>
            <ul class="nav navbar-nav navbar-right">
                
                {% if user.is_authenticated %}
                    <li><a href="{% url 'posts:create' %}">Post</a></li>
                    <li><a href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a href="{% url 'groups:create' %}">Create Group</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}
                    
            </ul>
        </div>
    </nav>

    <div class="container mycontent">
        {% block content %}
        {% endblock content %}
    </div>
    <canvas id="canvas"></canvas>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script type="text/javascript" src="{% static 'orbit_connect/js/master.js' %}"></script>
        
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to OrbitConnect!</h1>

{% endblock content %}
    

templates/test.html
{% extends 'base.html' %}

{% block content %}

<h1>You are now logged in!</h1>
    
{% endblock content %}
    

templates/thanks.html
{% extends 'base.html' %}

{% block content %}

<h1>Thanks for visiting, come back soon!</h1>
    
{% endblock content %}
    